//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseMapWeb.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CourseMapDataModel : DbContext
    {
        public CourseMapDataModel()
            : base("name=CourseMapDataModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<State> States { get; set; }
        public DbSet<CourseInformation> CourseInformations { get; set; }
        public DbSet<DepartmentsInformation> DepartmentsInformations { get; set; }
        public DbSet<ElectiveInformation> ElectiveInformations { get; set; }
        public DbSet<MajorInformation> MajorInformations { get; set; }
        public DbSet<PrerequisiteCourseInformation> PrerequisiteCourseInformations { get; set; }
        public DbSet<SchoolCollageInformation> SchoolCollageInformations { get; set; }
        public DbSet<StudentBasicInformation> StudentBasicInformations { get; set; }
        public DbSet<StudentCourseInformation> StudentCourseInformations { get; set; }
        public DbSet<StudentElectiveCours> StudentElectiveCourses { get; set; }
        public DbSet<StudentPrerequisiteCours> StudentPrerequisiteCourses { get; set; }
    }
}
