//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseMapWeb.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseInformation
    {
        public CourseInformation()
        {
            this.ElectiveInformations = new HashSet<ElectiveInformation>();
            this.PrerequisiteCourseInformations = new HashSet<PrerequisiteCourseInformation>();
            this.StudentCourseInformations = new HashSet<StudentCourseInformation>();
        }
    
        public long Id { get; set; }
        public long MajorId { get; set; }
        public string CourseName { get; set; }
        public string PassingGrade { get; set; }
        public int Unit { get; set; }
    
        public virtual MajorInformation MajorInformation { get; set; }
        public virtual ICollection<ElectiveInformation> ElectiveInformations { get; set; }
        public virtual ICollection<PrerequisiteCourseInformation> PrerequisiteCourseInformations { get; set; }
        public virtual ICollection<StudentCourseInformation> StudentCourseInformations { get; set; }
    }
}
