//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseMapWeb.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentsInformation
    {
        public DepartmentsInformation()
        {
            this.MajorInformations = new HashSet<MajorInformation>();
        }
    
        public long Id { get; set; }
        public long SchoolOrCollageId { get; set; }
        public string DepartmentName { get; set; }
    
        public virtual SchoolCollageInformation SchoolCollageInformation { get; set; }
        public virtual ICollection<MajorInformation> MajorInformations { get; set; }
    }
}
