//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseMapWeb.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectiveInformation
    {
        public ElectiveInformation()
        {
            this.StudentElectiveCourses = new HashSet<StudentElectiveCours>();
        }
    
        public long Id { get; set; }
        public long CourseId { get; set; }
        public string ElectiveName { get; set; }
        public string PassingGrade { get; set; }
        public int Score { get; set; }
    
        public virtual CourseInformation CourseInformation { get; set; }
        public virtual ICollection<StudentElectiveCours> StudentElectiveCourses { get; set; }
    }
}
