//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseMapWeb.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolCollageInformation
    {
        public SchoolCollageInformation()
        {
            this.DepartmentsInformations = new HashSet<DepartmentsInformation>();
            this.StudentBasicInformations = new HashSet<StudentBasicInformation>();
        }
    
        public long Id { get; set; }
        public string SchoolOrCollageName { get; set; }
        public string TypeSc { get; set; }
    
        public virtual ICollection<DepartmentsInformation> DepartmentsInformations { get; set; }
        public virtual ICollection<StudentBasicInformation> StudentBasicInformations { get; set; }
    }
}
