//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseMapWeb.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentBasicInformation
    {
        public StudentBasicInformation()
        {
            this.StudentCourseInformations = new HashSet<StudentCourseInformation>();
            this.StudentElectiveCourses = new HashSet<StudentElectiveCours>();
            this.StudentPrerequisiteCourses = new HashSet<StudentPrerequisiteCours>();
        }
    
        public long Id { get; set; }
        public string StudentId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string SchoolOrCollage { get; set; }
        public long SchoolOrCollageId { get; set; }
        public long DepartmentId { get; set; }
        public long MajorId { get; set; }
        public System.DateTime Dob { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
    
        public virtual SchoolCollageInformation SchoolCollageInformation { get; set; }
        public virtual ICollection<StudentCourseInformation> StudentCourseInformations { get; set; }
        public virtual ICollection<StudentElectiveCours> StudentElectiveCourses { get; set; }
        public virtual ICollection<StudentPrerequisiteCours> StudentPrerequisiteCourses { get; set; }
    }
}
