//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseMapWeb.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentPrerequisiteCours
    {
        public long Id { get; set; }
        public long StudentId { get; set; }
        public long PrerequisiteCourseId { get; set; }
        public string PrerequisiteCourseStatus { get; set; }
    
        public virtual PrerequisiteCourseInformation PrerequisiteCourseInformation { get; set; }
        public virtual StudentBasicInformation StudentBasicInformation { get; set; }
    }
}
